#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
为单词数据文件添加例句中文翻译
基于英文例句自动生成中文翻译
"""

import re
import json

# 定义常见句型的中文翻译模板
translation_patterns = {
    # 基础句型
    r"^I have a (\w+)\.$": lambda m: f"我有一{m.group(1)}。",
    r"^I have (\d+) (\w+)s?\.$": lambda m: f"我有{m.group(1)}个{m.group(2)}。",
    r"^This is my (\w+)\.$": lambda m: f"这是我的{m.group(1)}。",
    r"^This is a (\w+)\.$": lambda m: f"这是一个{m.group(1)}。",
    r"^The (\w+) is (\w+)\.$": lambda m: f"这个{m.group(1)}是{m.group(2)}的。",
    r"^I like (\w+)\.$": lambda m: f"我喜欢{m.group(1)}。",
    r"^I love my (\w+)\.$": lambda m: f"我爱我的{m.group(1)}。",
    r"^Look at (\w+)\.$": lambda m: f"看{m.group(1)}。",
    r"^Look at my (\w+)\.$": lambda m: f"看我的{m.group(1)}。",
    r"^Look at the (\w+)\.$": lambda m: f"看这个{m.group(1)}。",
    r"^Touch your (\w+)\.$": lambda m: f"摸你的{m.group(1)}。",
    r"^Open your (\w+)\.$": lambda m: f"打开你的{m.group(1)}。",
    r"^Close your (\w+)\.$": lambda m: f"闭上你的{m.group(1)}。",
    r"^Show me your (\w+)\.$": lambda m: f"给我看看你的{m.group(1)}。",
    r"^What's your (\w+)\?$": lambda m: f"你的{m.group(1)}是什么？",
    r"^Where is my (\w+)\?$": lambda m: f"我的{m.group(1)}在哪里？",
    r"^Where are my (\w+)s?\?$": lambda m: f"我的{m.group(1)}在哪里？",
    r"^I'm from (\w+)\.$": lambda m: f"我来自{m.group(1)}。",
    r"^She is (\w+)\.$": lambda m: f"她是{m.group(1)}。",
    r"^He is (\w+)\.$": lambda m: f"他是{m.group(1)}。",
    r"^They are (\w+)\.$": lambda m: f"他们是{m.group(1)}。",
    r"^We are (\w+)\.$": lambda m: f"我们是{m.group(1)}。",
    r"^You are (\w+)\.$": lambda m: f"你是{m.group(1)}。",
    r"^It's (\w+)\.$": lambda m: f"它是{m.group(1)}。",
    r"^It's a (\w+)\.$": lambda m: f"它是一只{m.group(1)}。",
    r"^It's an (\w+)\.$": lambda m: f"它是一个{m.group(1)}。",
    r"^It's the (\w+)\.$": lambda m: f"它是这个{m.group(1)}。",
    r"^Let's (\w+)\.$": lambda m: f"让我们{m.group(1)}。",
    r"^Let's go to (\w+)\.$": lambda m: f"让我们去{m.group(1)}。",
    r"^Can I (\w+)\?$": lambda m: f"我能{m.group(1)}吗？",
    r"^Do you like (\w+)\?$": lambda m: f"你喜欢{m.group(1)}吗？",
    r"^Do you have (\w+)\?$": lambda m: f"你有{m.group(1)}吗？",
    r"^Have some (\w+)\.$": lambda m: f"吃些{m.group(1)}。",
    r"^Eat some (\w+)\.$": lambda m: f"吃些{m.group(1)}。",
    r"^Drink some (\w+)\.$": lambda m: f"喝些{m.group(1)}。",
    r"^Pass me the (\w+)\.$": lambda m: f"把{m.group(1)}递给我。",
    r"^Put on your (\w+)\.$": lambda m: f"戴上你的{m.group(1)}。",
    r"^Take off your (\w+)\.$": lambda m: f"脱下你的{m.group(1)}。",
    r"^Go to (\w+)\.$": lambda m: f"去{m.group(1)}。",
    r"^Come (\w+)\.$": lambda m: f"过来{m.group(1)}。",
    r"^Wave your (\w+)\.$": lambda m: f"挥动你的{m.group(1)}。",
    r"^Shake your (\w+)\.$": lambda m: f"摇动你的{m.group(1)}。",
    r"^Stamp your (\w+)\.$": lambda m: f"跺你的{m.group(1)}。",
    r"^Clap your (\w+)\.$": lambda m: f"拍拍你的{m.group(1)}。",
    r"^Bounce the (\w+)\.$": lambda m: f"拍{m.group(1)}。",
    r"^Drive a (\w+)\.$": lambda m: f"开{m.group(1)}。",
    r"^Row a (\w+)\.$": lambda m: f"划{m.group(1)}。",
    r"^Read a (\w+)\.$": lambda m: f"读{m.group(1)}。",
    r"^I see (\d+)\.$": lambda m: f"我看见{m.group(1)}个。",
    r"^I am (\d+)\.$": lambda m: f"我{m.group(1)}岁了。",
    r"^I want (\w+)\.$": lambda m: f"我想要{m.group(1)}。",
    r"^I want to (\w+)\.$": lambda m: f"我想要{m.group(1)}。",
    r"^I want some (\w+)\.$": lambda m: f"我想要一些{m.group(1)}。",
    r"^I'd like some (\w+)\.$": lambda m: f"我想要一些{m.group(1)}。",
    r"^I love to (\w+)\.$": lambda m: f"我喜欢{m.group(1)}。",
    r"^I like to (\w+)\.$": lambda m: f"我喜欢{m.group(1)}。",
    r"^I often (\w+)\.$": lambda m: f"我经常{m.group(1)}。",
    r"^I usually (\w+)\.$": lambda m: f"我通常{m.group(1)}。",
    r"^I sometimes (\w+)\.$": lambda m: f"我有时{m.group(1)}。",
    r"^I can (\w+)\.$": lambda m: f"我能{m.group(1)}。",
    r"^I can't (\w+)\.$": lambda m: f"我不能{m.group(1)}。",
    r"^I don't (\w+)\.$": lambda m: f"我不{m.group(1)}。",
    r"^I didn't (\w+)\.$": lambda m: f"我没有{m.group(1)}。",
    r"^I went to (\w+)\.$": lambda m: f"我去了{m.group(1)}。",
    r"^I went (\w+)\.$": lambda m: f"我去{m.group(1)}了。",
    r"^I saw (\w+)\.$": lambda m: f"我看见了{m.group(1)}。",
    r"^I ate (\w+)\.$": lambda m: f"我吃了{m.group(1)}。",
    r"^I drank (\w+)\.$": lambda m: f"我喝了{m.group(1)}。",
    r"^I bought (\w+)\.$": lambda m: f"我买了{m.group(1)}。",
    r"^I took (\w+)\.$": lambda m: f"我带了{m.group(1)}。",
    r"^I took (\w+) pictures\.$": lambda m: f"我拍了{m.group(1)}照片。",
    r"^I hurt my (\w+)\.$": lambda m: f"我伤了我的{m.group(1)}。",
    r"^I lost my (\w+)\.$": lambda m: f"我丢了我的{m.group(1)}。",
    r"^I found my (\w+)\.$": lambda m: f"我找到了我的{m.group(1)}。",
    r"^I fixed my (\w+)\.$": lambda m: f"我修好了我的{m.group(1)}。",
    r"^I cleaned my (\w+)\.$": lambda m: f"我打扫了我的{m.group(1)}。",
    r"^I washed my (\w+)\.$": lambda m: f"我洗了我的{m.group(1)}。",
    r"^I watched (\w+)\.$": lambda m: f"我看了{m.group(1)}。",
    r"^I read (\w+)\.$": lambda m: f"我读了{m.group(1)}。",
    r"^I stayed at (\w+)\.$": lambda m: f"我待在{m.group(1)}。",
    r"^I slept (\w+)\.$": lambda m: f"我睡得{m.group(1)}。",
    r"^I had (\w+)\.$": lambda m: f"我有{m.group(1)}。",
    r"^I had a (\w+)\.$": lambda m: f"我{m.group(1)}了。",
    r"^I played (\w+)\.$": lambda m: f"我玩了{m.group(1)}。",
    r"^I played (\w+) with (\w+)\.$": lambda m: f"我和{m.group(2)}玩了{m.group(1)}。",
    r"^I went (\w+) with my (\w+)\.$": lambda m: f"我和我的{m.group(2)}去{m.group(1)}了。",
    r"^I went to (\w+) with my (\w+)\.$": lambda m: f"我和我的{m.group(2)}去了{m.group(1)}。",
    r"^I (\w+) with my (\w+)\.$": lambda m: f"我和我的{m.group(2)}{m.group(1)}。",
    r"^My (\w+) is (\w+)\.$": lambda m: f"我的{m.group(1)}是{m.group(2)}的。",
    r"^My (\w+) has (\w+)\.$": lambda m: f"我的{m.group(1)}有{m.group(2)}。",
    r"^My (\w+) can (\w+)\.$": lambda m: f"我的{m.group(1)}会{m.group(2)}。",
    r"^Her (\w+) is (\w+)\.$": lambda m: f"她的{m.group(1)}是{m.group(2)}的。",
    r"^His (\w+) is (\w+)\.$": lambda m: f"他的{m.group(1)}是{m.group(2)}的。",
    r"^She has (\w+) (\w+)\.$": lambda m: f"她有{m.group(1)}{m.group(2)}。",
    r"^He has (\w+) (\w+)\.$": lambda m: f"他有{m.group(1)}{m.group(2)}。",
    r"^She is a (\w+)\.$": lambda m: f"她是一名{m.group(1)}。",
    r"^He is a (\w+)\.$": lambda m: f"他是一名{m.group(1)}。",
    r"^This is (\w+) (\w+)\.$": lambda m: f"这是{m.group(1)}{m.group(2)}。",
    r"^That is (\w+) (\w+)\.$": lambda m: f"那是{m.group(1)}{m.group(2)}。",
    r"^These are (\w+) (\w+)s?\.$": lambda m: f"这些是{m.group(1)}{m.group(2)}。",
    r"^Those are (\w+) (\w+)s?\.$": lambda m: f"那些是{m.group(1)}{m.group(2)}。",
    r"^Who's that (\w+)\?$": lambda m: f"那个{m.group(1)}是谁？",
    r"^What's this\?$": lambda m: f"这是什么？",
    r"^What's that\?$": lambda m: f"那是什么？",
    r"^What colour is it\?$": lambda m: f"它是什么颜色的？",
    r"^What time is it\?$": lambda m: f"几点了？",
    r"^How many (\w+)\?$": lambda m: f"多少{m.group(1)}？",
    r"^How old are you\?$": lambda m: f"你多大了？",
    r"^How are you\?$": lambda m: f"你好吗？",
    r"^How do you feel\?$": lambda m: f"你感觉怎么样？",
    r"^How does (\w+) feel\?$": lambda m: f"{m.group(1)}感觉怎么样？",
    r"^How can I get (\w+)\?$": lambda m: f"我怎么去{m.group(1)}？",
    r"^How tall are you\?$": lambda m: f"你多高？",
    r"^How heavy are you\?$": lambda m: f"你多重？",
    r"^Where is the (\w+)\?$": lambda m: f"{m.group(1)}在哪里？",
    r"^Where are you going\?$": lambda m: f"你要去哪里？",
    r"^Where did you go\?$": lambda m: f"你去哪里了？",
    r"^When do you (\w+)\?$": lambda m: f"你什么时候{m.group(1)}？",
    r"^What do you (\w+)\?$": lambda m: f"你{m.group(1)}什么？",
    r"^What did you (\w+)\?$": lambda m: f"你{m.group(1)}了什么？",
    r"^What are you going to (\w+)\?$": lambda m: f"你打算{m.group(1)}什么？",
    r"^What are you doing\?$": lambda m: f"你在做什么？",
    r"^What is (\w+) doing\?$": lambda m: f"{m.group(1)}在做什么？",
    r"^Is it (\w+)\?$": lambda m: f"它是{m.group(1)}的吗？",
    r"^Is this (\w+)\?$": lambda m: f"这是{m.group(1)}吗？",
    r"^Is that (\w+)\?$": lambda m: f"那是{m.group(1)}吗？",
    r"^Are you (\w+)\?$": lambda m: f"你是{m.group(1)}吗？",
    r"^Can you (\w+)\?$": lambda m: f"你能{m.group(1)}吗？",
    r"^Can I (\w+) you\?$": lambda m: f"我能{m.group(1)}你吗？",
    r"^May I (\w+)\?$": lambda m: f"我可以{m.group(1)}吗？",
    r"^Shall we (\w+)\?$": lambda m: f"我们{m.group(1)}好吗？",
    r"^Let's (\w+) together\.$": lambda m: f"让我们一起{m.group(1)}。",
    r"^Don't (\w+)\.$": lambda m: f"不要{m.group(1)}。",
    r"^Please (\w+)\.$": lambda m: f"请{m.group(1)}。",
    r"^Thank you\.$": lambda m: f"谢谢你。",
    r"^You're welcome\.$": lambda m: f"不客气。",
    r"^Excuse me\.$": lambda m: f"打扰一下。",
    r"^I'm sorry\.$": lambda m: f"对不起。",
    r"^That's OK\.$": lambda m: f"没关系。",
    r"^That's all right\.$": lambda m: f"没关系。",
    r"^Good morning\.$": lambda m: f"早上好。",
    r"^Good afternoon\.$": lambda m: f"下午好。",
    r"^Good evening\.$": lambda m: f"晚上好。",
    r"^Good night\.$": lambda m: f"晚安。",
    r"^Goodbye\.$": lambda m: f"再见。",
    r"^See you\.$": lambda m: f"再见。",
    r"^See you later\.$": lambda m: f"回头见。",
    r"^See you tomorrow\.$": lambda m: f"明天见。",
    r"^Have a good time\.$": lambda m: f"玩得开心。",
    r"^Have fun\.$": lambda m: f"玩得开心。",
    r"^Be careful\.$": lambda m: f"小心。",
    r"^Hurry up\.$": lambda m: f"快点。",
    r"^Come on\.$": lambda m: f"加油/快点。",
    r"^Well done\.$": lambda m: f"做得好。",
    r"^Good job\.$": lambda m: f"做得好。",
    r"^Great\.$": lambda m: f"太棒了。",
    r"^Wonderful\.$": lambda m: f"太棒了。",
    r"^Excellent\.$": lambda m: f"太棒了。",
    r"^Perfect\.$": lambda m: f"完美。",
    r"^Really\?$": lambda m: f"真的吗？",
    r"^Sure\.$": lambda m: f"当然。",
    r"^OK\.$": lambda m: f"好的。",
    r"^Yes\.$": lambda m: f"是的。",
    r"^No\.$": lambda m: f"不。",
    r"^Right\.$": lambda m: f"对的。",
    r"^Wrong\.$": lambda m: f"错的。",
    r"^True\.$": lambda m: f"真的。",
    r"^False\.$": lambda m: f"假的。",
    r"^Maybe\.$": lambda m: f"也许。",
    r"^Perhaps\.$": lambda m: f"也许。",
    r"^Probably\.$": lambda m: f"可能。",
    r"^Certainly\.$": lambda m: f"当然。",
    r"^Of course\.$": lambda m: f"当然。",
    r"^Why not\?$": lambda m: f"为什么不呢？",
    r"^What for\?$": lambda m: f"为什么？",
    r"^How come\?$": lambda m: f"怎么会？",
    r"^So what\?$": lambda m: f"那又怎样？",
    r"^Who knows\?$": lambda m: f"谁知道呢？",
    r"^Guess what\?$": lambda m: f"你猜怎么着？",
    r"^You know\?$": lambda m: f"你知道吗？",
    r"^You see\?$": lambda m: f"你明白吗？",
    r"^I see\.$": lambda m: f"我明白了。",
    r"^I know\.$": lambda m: f"我知道。",
    r"^I think so\.$": lambda m: f"我想是的。",
    r"^I don't think so\.$": lambda m: f"我不这么认为。",
    r"^I hope so\.$": lambda m: f"我希望如此。",
    r"^I hope not\.$": lambda m: f"我希望不是。",
    r"^I believe so\.$": lambda m: f"我相信如此。",
    r"^I wonder\.$": lambda m: f"我想知道。",
    r"^I forget\.$": lambda m: f"我忘了。",
    r"^I remember\.$": lambda m: f"我记得。",
    r"^I understand\.$": lambda m: f"我理解。",
    r"^I agree\.$": lambda m: f"我同意。",
    r"^I disagree\.$": lambda m: f"我不同意。",
    r"^It depends\.$": lambda m: f"看情况。",
    r"^It's up to you\.$": lambda m: f"由你决定。",
    r"^It's your turn\.$": lambda m: f"轮到你了。",
    r"^It's my turn\.$": lambda m: f"轮到我了。",
    r"^It's time to (\w+)\.$": lambda m: f"该{m.group(1)}了。",
    r"^It's time for (\w+)\.$": lambda m: f"该{m.group(1)}了。",
    r"^It's (\d+) o'clock\.$": lambda m: f"现在{m.group(1)}点了。",
    r"^It's (\w+) today\.$": lambda m: f"今天是{m.group(1)}。",
    r"^It's (\w+) now\.$": lambda m: f"现在是{m.group(1)}。",
    r"^It's getting (\w+)\.$": lambda m: f"天气变得{m.group(1)}了。",
    r"^It's going to (\w+)\.$": lambda m: f"将要{m.group(1)}。",
    r"^There is (\w+)\.$": lambda m: f"有{m.group(1)}。",
    r"^There are (\w+)\.$": lambda m: f"有{m.group(1)}。",
    r"^There was (\w+)\.$": lambda m: f"曾经有{m.group(1)}。",
    r"^There were (\w+)\.$": lambda m: f"曾经有{m.group(1)}。",
    r"^There is no (\w+)\.$": lambda m: f"没有{m.group(1)}。",
    r"^There are no (\w+)\.$": lambda m: f"没有{m.group(1)}。",
    r"^There was no (\w+)\.$": lambda m: f"曾经没有{m.group(1)}。",
    r"^There were no (\w+)\.$": lambda m: f"曾经没有{m.group(1)}。",
    r"^Here you are\.$": lambda m: f"给你。",
    r"^Here it is\.$": lambda m: f"在这里。",
    r"^Here they are\.$": lambda m: f"他们在这里。",
    r"^Here we go\.$": lambda m: f"我们走吧。",
    r"^Follow me\.$": lambda m: f"跟我来。",
    r"^Come with me\.$": lambda m: f"跟我来。",
    r"^Go away\.$": lambda m: f"走开。",
    r"^Get out\.$": lambda m: f"出去。",
    r"^Get up\.$": lambda m: f"起床。",
    r"^Go to bed\.$": lambda m: f"去睡觉。",
    r"^Go to sleep\.$": lambda m: f"去睡觉。",
    r"^Wake up\.$": lambda m: f"醒来。",
    r"^Stand up\.$": lambda m: f"站起来。",
    r"^Sit down\.$": lambda m: f"坐下。",
    r"^Turn around\.$": lambda m: f"转身。",
    r"^Turn left\.$": lambda m: f"左转。",
    r"^Turn right\.$": lambda m: f"右转。",
    r"^Go straight\.$": lambda m: f"直走。",
    r"^Go back\.$": lambda m: f"回去。",
    r"^Go ahead\.$": lambda m: f"继续。",
    r"^Go on\.$": lambda m: f"继续。",
    r"^Hold on\.$": lambda m: f"等一下。",
    r"^Wait a minute\.$": lambda m: f"等一下。",
    r"^Just a minute\.$": lambda m: f"等一下。",
    r"^One moment\.$": lambda m: f"等一下。",
    r"^Take your time\.$": lambda m: f"慢慢来。",
    r"^No problem\.$": lambda m: f"没问题。",
    r"^No way\.$": lambda m: f"不可能。",
    r"^Never mind\.$": lambda m: f"没关系。",
    r"^It doesn't matter\.$": lambda m: f"没关系。",
    r"^Forget it\.$": lambda m: f"算了。",
    r"^That's it\.$": lambda m: f"就是这样。",
    r"^That's all\.$": lambda m: f"就这样。",
    r"^All right\.$": lambda m: f"好的。",
    r"^Very good\.$": lambda m: f"很好。",
    r"^Pretty good\.$": lambda m: f"很好。",
    r"^Not bad\.$": lambda m: f"不错。",
    r"^Not good\.$": lambda m: f"不好。",
    r"^So so\.$": lambda m: f"一般般。",
    r"^Just so so\.$": lambda m: f"一般般。",
    r"^More or less\.$": lambda m: f"差不多。",
    r"^Almost\.$": lambda m: f"几乎。",
    r"^Exactly\.$": lambda m: f"正是。",
    r"^Absolutely\.$": lambda m: f"绝对。",
    r"^Definitely\.$": lambda m: f"肯定。",
    r"^Actually\.$": lambda m: f"实际上。",
    r"^In fact\.$": lambda m: f"事实上。",
    r"^As a matter of fact\.$": lambda m: f"事实上。",
    r"^By the way\.$": lambda m: f"顺便说一下。",
    r"^In other words\.$": lambda m: f"换句话说。",
    r"^In short\.$": lambda m: f"简而言之。",
    r"^In brief\.$": lambda m: f"简而言之。",
    r"^In conclusion\.$": lambda m: f"总之。",
    r"^To sum up\.$": lambda m: f"总之。",
    r"^All in all\.$": lambda m: f"总之。",
    r"^On the whole\.$": lambda m: f"总的来说。",
    r"^In general\.$": lambda m: f"一般来说。",
    r"^Generally speaking\.$": lambda m: f"一般来说。",
    r"^Frankly speaking\.$": lambda m: f"坦白说。",
    r"^Honestly speaking\.$": lambda m: f"老实说。",
    r"^Strictly speaking\.$": lambda m: f"严格来说。",
    r"^Roughly speaking\.$": lambda m: f"粗略地说。",
    r"^Broadly speaking\.$": lambda m: f"广义地说。",
    r"^Narrowly speaking\.$": lambda m: f"狭义地说。",
    r"^Technically speaking\.$": lambda m: f"技术上来说。",
    r"^Theoretically speaking\.$": lambda m: f"理论上来说。",
    r"^Practically speaking\.$": lambda m: f"实际上来说。",
    r"^Realistically speaking\.$": lambda m: f"现实来说。",
    r"^Ideally speaking\.$": lambda m: f"理想来说。",
    r"^Naturally\.$": lambda m: f"自然地。",
    r"^Obviously\.$": lambda m: f"显然。",
    r"^Clearly\.$": lambda m: f"清楚地。",
    r"^Apparently\.$": lambda m: f"显然。",
    r"^Evidently\.$": lambda m: f"明显地。",
    r"^Presumably\.$": lambda m: f"大概。",
    r"^Supposedly\.$": lambda m: f" supposedly。",
    r"^Hopefully\.$": lambda m: f"希望如此。",
    r"^Luckily\.$": lambda m: f"幸运地。",
    r"^Fortunately\.$": lambda m: f"幸运地。",
    r"^Unfortunately\.$": lambda m: f"不幸地。",
    r"^Surprisingly\.$": lambda m: f"令人惊讶地。",
    r"^Amazingly\.$": lambda m: f"令人惊讶地。",
    r"^Interestingly\.$": lambda m: f"有趣地。",
    r"^Excitingly\.$": lambda m: f"令人兴奋地。",
    r"^Disappointingly\.$": lambda m: f"令人失望地。",
    r"^Encouragingly\.$": lambda m: f"令人鼓舞地。",
    r"^Alarmingly\.$": lambda m: f"令人担忧地。",
    r"^Disturbingly\.$": lambda m: f"令人不安地。",
    r"^Worryingly\.$": lambda m: f"令人担忧地。",
    r"^Remarkably\.$": lambda m: f"显著地。",
    r"^Notably\.$": lambda m: f"显著地。",
    r"^Significantly\.$": lambda m: f"显著地。",
    r"^Importantly\.$": lambda m: f"重要地。",
    r"^Essentially\.$": lambda m: f"本质上。",
    r"^Basically\.$": lambda m: f"基本上。",
    r"^Fundamentally\.$": lambda m: f"根本上。",
    r"^Primarily\.$": lambda m: f"主要地。",
    r"^Mainly\.$": lambda m: f"主要地。",
    r"^Largely\.$": lambda m: f"很大程度上。",
    r"^Partly\.$": lambda m: f"部分地。",
    r"^Partially\.$": lambda m: f"部分地。",
    r"^Fully\.$": lambda m: f"完全地。",
    r"^Completely\.$": lambda m: f"完全地。",
    r"^Totally\.$": lambda m: f"完全地。",
    r"^Entirely\.$": lambda m: f"完全地。",
    r"^Wholly\.$": lambda m: f"完全地。",
    r"^Utterly\.$": lambda m: f"完全地。",
    r"^Absolutely\.$": lambda m: f"绝对地。",
    r"^Thoroughly\.$": lambda m: f"彻底地。",
    r"^Extremely\.$": lambda m: f"极其。",
    r"^Highly\.$": lambda m: f"高度地。",
    r"^Greatly\.$": lambda m: f"非常。",
    r"^Deeply\.$": lambda m: f"深深地。",
    r"^Strongly\.$": lambda m: f"强烈地。",
    r"^Seriously\.$": lambda m: f"认真地。",
    r"^Severely\.$": lambda m: f"严重地。",
    r"^Badly\.$": lambda m: f"非常。",
    r"^Terribly\.$": lambda m: f"非常。",
    r"^Awfully\.$": lambda m: f"非常。",
    r"^Dreadfully\.$": lambda m: f"可怕地。",
    r"^Horribly\.$": lambda m: f"可怕地。",
    r"^Frightfully\.$": lambda m: f"可怕地。",
    r"^Incredibly\.$": lambda m: f"难以置信地。",
    r"^Unbelievably\.$": lambda m: f"难以置信地。",
    r"^Extraordinarily\.$": lambda m: f"非凡地。",
    r"^Exceptionally\.$": lambda m: f"异常地。",
    r"^Unusually\.$": lambda m: f"不寻常地。",
    r"^Abnormally\.$": lambda m: f"异常地。",
    r"^Slightly\.$": lambda m: f"稍微。",
    r"^Somewhat\.$": lambda m: f"有点。",
    r"^Rather\.$": lambda m: f"相当。",
    r"^Quite\.$": lambda m: f"相当。",
    r"^Pretty\.$": lambda m: f"相当。",
    r"^Fairly\.$": lambda m: f"相当。",
    r"^Relatively\.$": lambda m: f"相对地。",
    r"^Comparatively\.$": lambda m: f"比较地。",
    r"^Equally\.$": lambda m: f"同样地。",
    r"^Similarly\.$": lambda m: f"同样地。",
    r"^Likewise\.$": lambda m: f"同样地。",
    r"^Otherwise\.$": lambda m: f"否则。",
    r"^Conversely\.$": lambda m: f"相反地。",
    r"^Alternatively\.$": lambda m: f"或者。",
    r"^Instead\.$": lambda m: f"代替。",
    r"^Besides\.$": lambda m: f"此外。",
    r"^Moreover\.$": lambda m: f"此外。",
    r"^Furthermore\.$": lambda m: f"此外。",
    r"^Additionally\.$": lambda m: f"此外。",
    r"^Also\.$": lambda m: f"也。",
    r"^Too\.$": lambda m: f"也。",
    r"^Either\.$": lambda m: f"也。",
    r"^Neither\.$": lambda m: f"也不。",
    r"^Nor\.$": lambda m: f"也不。",
    r"^However\.$": lambda m: f"然而。",
    r"^Nevertheless\.$": lambda m: f"然而。",
    r"^Nonetheless\.$": lambda m: f"然而。",
    r"^Yet\.$": lambda m: f"然而。",
    r"^Still\.$": lambda m: f"仍然。",
    r"^Even so\.$": lambda m: f"即使如此。",
    r"^All the same\.$": lambda m: f"尽管如此。",
    r"^Regardless\.$": lambda m: f"不管。",
    r"^Irrespective\.$": lambda m: f"不管。",
    r"^Notwithstanding\.$": lambda m: f"尽管。",
    r"^Despite\.$": lambda m: f"尽管。",
    r"^In spite of\.$": lambda m: f"尽管。",
    r"^Although\.$": lambda m: f"虽然。",
    r"^Though\.$": lambda m: f"虽然。",
    r"^Even though\.$": lambda m: f"即使。",
    r"^Even if\.$": lambda m: f"即使。",
    r"^Whether\.$": lambda m: f"是否。",
    r"^Unless\.$": lambda m: f"除非。",
    r"^Until\.$": lambda m: f"直到。",
    r"^Till\.$": lambda m: f"直到。",
    r"^Since\.$": lambda m: f"自从。",
    r"^As\.$": lambda m: f"作为。",
    r"^Because\.$": lambda m: f"因为。",
    r"^Because of\.$": lambda m: f"因为。",
    r"^Due to\.$": lambda m: f"由于。",
    r"^Owing to\.$": lambda m: f"由于。",
    r"^Thanks to\.$": lambda m: f"多亏。",
    r"^According to\.$": lambda m: f"根据。",
    r"^Based on\.$": lambda m: f"基于。",
    r"^Depending on\.$": lambda m: f"取决于。",
    r"^Regardless of\.$": lambda m: f"不管。",
    r"^Irrespective of\.$": lambda m: f"不管。",
    r"^In terms of\.$": lambda m: f"就...而言。",
    r"^With regard to\.$": lambda m: f"关于。",
    r"^Regarding\.$": lambda m: f"关于。",
    r"^Concerning\.$": lambda m: f"关于。",
    r"^As for\.$": lambda m: f"至于。",
    r"^As to\.$": lambda m: f"至于。",
    r"^With respect to\.$": lambda m: f"关于。",
    r"^In respect of\.$": lambda m: f"关于。",
    r"^In connection with\.$": lambda m: f"与...有关。",
    r"^In relation to\.$": lambda m: f"与...有关。",
    r"^Relative to\.$": lambda m: f"相对于。",
    r"^Compared to\.$": lambda m: f"与...相比。",
    r"^Compared with\.$": lambda m: f"与...相比。",
    r"^In comparison with\.$": lambda m: f"与...相比。",
    r"^By comparison\.$": lambda m: f"相比之下。",
    r"^In contrast\.$": lambda m: f"相比之下。",
    r"^On the contrary\.$": lambda m: f"相反。",
    r"^Conversely\.$": lambda m: f"相反地。",
    r"^Alternatively\.$": lambda m: f"或者。",
    r"^On the other hand\.$": lambda m: f"另一方面。",
    r"^Instead of\.$": lambda m: f"代替。",
    r"^Rather than\.$": lambda m: f"而不是。",
    r"^Apart from\.$": lambda m: f"除了。",
    r"^Aside from\.$": lambda m: f"除了。",
    r"^Except for\.$": lambda m: f"除了。",
    r"^Except\.$": lambda m: f"除了。",
    r"^Excluding\.$": lambda m: f"不包括。",
    r"^Not including\.$": lambda m: f"不包括。",
    r"^Without\.$": lambda m: f"没有。",
    r"^Including\.$": lambda m: f"包括。",
    r"^Inclusive of\.$": lambda m: f"包括。",
    r"^Together with\.$": lambda m: f"连同。",
    r"^Along with\.$": lambda m: f"连同。",
    r"^As well as\.$": lambda m: f"以及。",
    r"^In addition to\.$": lambda m: f"除了...还有。",
    r"^Besides\.$": lambda m: f"此外。",
    r"^Plus\.$": lambda m: f"加。",
    r"^Minus\.$": lambda m: f"减。",
    r"^Times\.$": lambda m: f"乘。",
    r"^Divided by\.$": lambda m: f"除以。",
    r"^Equals\.$": lambda m: f"等于。",
    r"^Is equal to\.$": lambda m: f"等于。",
    r"^Amounts to\.$": lambda m: f"总计。",
    r"^Totals\.$": lambda m: f"总计。",
    r"^Sums up to\.$": lambda m: f"总计。",
    r"^Comes to\.$": lambda m: f"达到。",
    r"^Adds up to\.$": lambda m: f"加起来是。",
    r"^Comes out to\.$": lambda m: f"结果是。",
    r"^Works out to\.$": lambda m: f"计算结果是。",
    r"^Turns out to be\.$": lambda m: f"结果是。",
    r"^Proves to be\.$": lambda m: f"证明是。",
    r"^Happens to be\.$": lambda m: f"碰巧是。",
    r"^Seems to be\.$": lambda m: f"似乎是。",
    r"^Appears to be\.$": lambda m: f"似乎是。",
    r"^Looks like\.$": lambda m: f"看起来像。",
    r"^Sounds like\.$": lambda m: f"听起来像。",
    r"^Feels like\.$": lambda m: f"感觉像。",
    r"^Tastes like\.$": lambda m: f"尝起来像。",
    r"^Smells like\.$": lambda m: f"闻起来像。",
    r"^Seems like\.$": lambda m: f"似乎像。",
    r"^Looks as if\.$": lambda m: f"看起来好像。",
    r"^Sounds as if\.$": lambda m: f"听起来好像。",
    r"^Feels as if\.$": lambda m: f"感觉好像。",
    r"^Tastes as if\.$": lambda m: f"尝起来好像。",
    r"^Smells as if\.$": lambda m: f"闻起来好像。",
    r"^Seems as if\.$": lambda m: f"似乎好像。",
    r"^Looks\.$": lambda m: f"看起来。",
    r"^Sounds\.$": lambda m: f"听起来。",
    r"^Feels\.$": lambda m: f"感觉。",
    r"^Tastes\.$": lambda m: f"尝起来。",
    r"^Smells\.$": lambda m: f"闻起来。",
    r"^Seems\.$": lambda m: f"似乎。",
    r"^Appears\.$": lambda m: f"似乎。",
    r"^Looks good\.$": lambda m: f"看起来不错。",
    r"^Sounds good\.$": lambda m: f"听起来不错。",
    r"^Feels good\.$": lambda m: f"感觉不错。",
    r"^Tastes good\.$": lambda m: f"尝起来不错。",
    r"^Smells good\.$": lambda m: f"闻起来不错。",
    r"^Seems good\.$": lambda m: f"似乎不错。",
    r"^Looks bad\.$": lambda m: f"看起来不好。",
    r"^Sounds bad\.$": lambda m: f"听起来不好。",
    r"^Feels bad\.$": lambda m: f"感觉不好。",
    r"^Tastes bad\.$": lambda m: f"尝起来不好。",
    r"^Smells bad\.$": lambda m: f"闻起来不好。",
    r"^Seems bad\.$": lambda m: f"似乎不好。",
    r"^Looks great\.$": lambda m: f"看起来很棒。",
    r"^Sounds great\.$": lambda m: f"听起来很棒。",
    r"^Feels great\.$": lambda m: f"感觉很棒。",
    r"^Tastes great\.$": lambda m: f"尝起来很棒。",
    r"^Smells great\.$": lambda m: f"闻起来很棒。",
    r"^Seems great\.$": lambda m: f"似乎很棒。",
    r"^Looks wonderful\.$": lambda m: f"看起来很精彩。",
    r"^Sounds wonderful\.$": lambda m: f"听起来很精彩。",
    r"^Feels wonderful\.$": lambda m: f"感觉很精彩。",
    r"^Tastes wonderful\.$": lambda m: f"尝起来很精彩。",
    r"^Smells wonderful\.$": lambda m: f"闻起来很精彩。",
    r"^Seems wonderful\.$": lambda m: f"似乎很精彩。",
    r"^Looks terrible\.$": lambda m: f"看起来很糟糕。",
    r"^Sounds terrible\.$": lambda m: f"听起来很糟糕。",
    r"^Feels terrible\.$": lambda m: f"感觉很糟糕。",
    r"^Tastes terrible\.$": lambda m: f"尝起来很糟糕。",
    r"^Smells terrible\.$": lambda m: f"闻起来很糟糕。",
    r"^Seems terrible\.$": lambda m: f"似乎很糟糕。",
    r"^Looks delicious\.$": lambda m: f"看起来很好吃。",
    r"^Sounds delicious\.$": lambda m: f"听起来很好吃。",
    r"^Feels delicious\.$": lambda m: f"感觉很好吃。",
    r"^Tastes delicious\.$": lambda m: f"尝起来很好吃。",
    r"^Smells delicious\.$": lambda m: f"闻起来很好吃。",
    r"^Seems delicious\.$": lambda m: f"似乎很好吃。",
    r"^Looks beautiful\.$": lambda m: f"看起来很美。",
    r"^Sounds beautiful\.$": lambda m: f"听起来很美。",
    r"^Feels beautiful\.$": lambda m: f"感觉很美。",
    r"^Tastes beautiful\.$": lambda m: f"尝起来很美。",
    r"^Smells beautiful\.$": lambda m: f"闻起来很美。",
    r"^Seems beautiful\.$": lambda m: f"似乎很美。",
    r"^Looks ugly\.$": lambda m: f"看起来很丑。",
    r"^Sounds ugly\.$": lambda m: f"听起来很丑。",
    r"^Feels ugly\.$": lambda m: f"感觉很丑。",
    r"^Tastes ugly\.$": lambda m: f"尝起来很丑。",
    r"^Smells ugly\.$": lambda m: f"闻起来很丑。",
    r"^Seems ugly\.$": lambda m: f"似乎很丑。",
    r"^Looks interesting\.$": lambda m: f"看起来很有趣。",
    r"^Sounds interesting\.$": lambda m: f"听起来很有趣。",
    r"^Feels interesting\.$": lambda m: f"感觉很有趣。",
    r"^Tastes interesting\.$": lambda m: f"尝起来很有趣。",
    r"^Smells interesting\.$": lambda m: f"闻起来很有趣。",
    r"^Seems interesting\.$": lambda m: f"似乎很有趣。",
    r"^Looks boring\.$": lambda m: f"看起来很无聊。",
    r"^Sounds boring\.$": lambda m: f"听起来很无聊。",
    r"^Feels boring\.$": lambda m: f"感觉很无聊。",
    r"^Tastes boring\.$": lambda m: f"尝起来很无聊。",
    r"^Smells boring\.$": lambda m: f"闻起来很无聊。",
    r"^Seems boring\.$": lambda m: f"似乎很无聊。",
    r"^Looks exciting\.$": lambda m: f"看起来很刺激。",
    r"^Sounds exciting\.$": lambda m: f"听起来很刺激。",
    r"^Feels exciting\.$": lambda m: f"感觉很刺激。",
    r"^Tastes exciting\.$": lambda m: f"尝起来很刺激。",
    r"^Smells exciting\.$": lambda m: f"闻起来很刺激。",
    r"^Seems exciting\.$": lambda m: f"似乎很刺激。",
    r"^Looks frightening\.$": lambda m: f"看起来很可怕。",
    r"^Sounds frightening\.$": lambda m: f"听起来很可怕。",
    r"^Feels frightening\.$": lambda m: f"感觉很可怕。",
    r"^Tastes frightening\.$": lambda m: f"尝起来很可怕。",
    r"^Smells frightening\.$": lambda m: f"闻起来很可怕。",
    r"^Seems frightening\.$": lambda m: f"似乎很可怕。",
    r"^Looks scary\.$": lambda m: f"看起来很吓人。",
    r"^Sounds scary\.$": lambda m: f"听起来很吓人。",
    r"^Feels scary\.$": lambda m: f"感觉很吓人。",
    r"^Tastes scary\.$": lambda m: f"尝起来很吓人。",
    r"^Smells scary\.$": lambda m: f"闻起来很吓人。",
    r"^Seems scary\.$": lambda m: f"似乎很吓人。",
    r"^Looks dangerous\.$": lambda m: f"看起来很危险。",
    r"^Sounds dangerous\.$": lambda m: f"听起来很危险。",
    r"^Feels dangerous\.$": lambda m: f"感觉很危险。",
    r"^Tastes dangerous\.$": lambda m: f"尝起来很危险。",
    r"^Smells dangerous\.$": lambda m: f"闻起来很危险。",
    r"^Seems dangerous\.$": lambda m: f"似乎很危险。",
    r"^Looks safe\.$": lambda m: f"看起来很安全。",
    r"^Sounds safe\.$": lambda m: f"听起来很安全。",
    r"^Feels safe\.$": lambda m: f"感觉很安全。",
    r"^Tastes safe\.$": lambda m: f"尝起来很安全。",
    r"^Smells safe\.$": lambda m: f"闻起来很安全。",
    r"^Seems safe\.$": lambda m: f"似乎很安全。",
    r"^Looks comfortable\.$": lambda m: f"看起来很舒服。",
    r"^Sounds comfortable\.$": lambda m: f"听起来很舒服。",
    r"^Feels comfortable\.$": lambda m: f"感觉很舒服。",
    r"^Tastes comfortable\.$": lambda m: f"尝起来很舒服。",
    r"^Smells comfortable\.$": lambda m: f"闻起来很舒服。",
    r"^Seems comfortable\.$": lambda m: f"似乎很舒服。",
    r"^Looks uncomfortable\.$": lambda m: f"看起来不舒服。",
    r"^Sounds uncomfortable\.$": lambda m: f"听起来不舒服。",
    r"^Feels uncomfortable\.$": lambda m: f"感觉不舒服。",
    r"^Tastes uncomfortable\.$": lambda m: f"尝起来不舒服。",
    r"^Smells uncomfortable\.$": lambda m: f"闻起来不舒服。",
    r"^Seems uncomfortable\.$": lambda m: f"似乎不舒服。",
    r"^Looks easy\.$": lambda m: f"看起来很容易。",
    r"^Sounds easy\.$": lambda m: f"听起来很容易。",
    r"^Feels easy\.$": lambda m: f"感觉很容易。",
    r"^Tastes easy\.$": lambda m: f"尝起来很容易。",
    r"^Smells easy\.$": lambda m: f"闻起来很容易。",
    r"^Seems easy\.$": lambda m: f"似乎很容易。",
    r"^Looks difficult\.$": lambda m: f"看起来很难。",
    r"^Sounds difficult\.$": lambda m: f"听起来很难。",
    r"^Feels difficult\.$": lambda m: f"感觉很难。",
    r"^Tastes difficult\.$": lambda m: f"尝起来很难。",
    r"^Smells difficult\.$": lambda m: f"闻起来很难。",
    r"^Seems difficult\.$": lambda m: f"似乎很难。",
    r"^Looks hard\.$": lambda m: f"看起来很难。",
    r"^Sounds hard\.$": lambda m: f"听起来很难。",
    r"^Feels hard\.$": lambda m: f"感觉很难。",
    r"^Tastes hard\.$": lambda m: f"尝起来很难。",
    r"^Smells hard\.$": lambda m: f"闻起来很难。",
    r"^Seems hard\.$": lambda m: f"似乎很难。",
    r"^Looks soft\.$": lambda m: f"看起来很软。",
    r"^Sounds soft\.$": lambda m: f"听起来很软。",
    r"^Feels soft\.$": lambda m: f"感觉很软。",
    r"^Tastes soft\.$": lambda m: f"尝起来很软。",
    r"^Smells soft\.$": lambda m: f"闻起来很软。",
    r"^Seems soft\.$": lambda m: f"似乎很软。",
    r"^Looks smooth\.$": lambda m: f"看起来很光滑。",
    r"^Sounds smooth\.$": lambda m: f"听起来很光滑。",
    r"^Feels smooth\.$": lambda m: f"感觉很光滑。",
    r"^Tastes smooth\.$": lambda m: f"尝起来很光滑。",
    r"^Smells smooth\.$": lambda m: f"闻起来很光滑。",
    r"^Seems smooth\.$": lambda m: f"似乎很光滑。",
    r"^Looks rough\.$": lambda m: f"看起来很粗糙。",
    r"^Sounds rough\.$": lambda m: f"听起来很粗糙。",
    r"^Feels rough\.$": lambda m: f"感觉很粗糙。",
    r"^Tastes rough\.$": lambda m: f"尝起来很粗糙。",
    r"^Smells rough\.$": lambda m: f"闻起来很粗糙。",
    r"^Seems rough\.$": lambda m: f"似乎很粗糙。",
    r"^Looks clean\.$": lambda m: f"看起来很干净。",
    r"^Sounds clean\.$": lambda m: f"听起来很干净。",
    r"^Feels clean\.$": lambda m: f"感觉很干净。",
    r"^Tastes clean\.$": lambda m: f"尝起来很干净。",
    r"^Smells clean\.$": lambda m: f"闻起来很干净。",
    r"^Seems clean\.$": lambda m: f"似乎很干净。",
    r"^Looks dirty\.$": lambda m: f"看起来很脏。",
    r"^Sounds dirty\.$": lambda m: f"听起来很脏。",
    r"^Feels dirty\.$": lambda m: f"感觉很脏。",
    r"^Tastes dirty\.$": lambda m: f"尝起来很脏。",
    r"^Smells dirty\.$": lambda m: f"闻起来很脏。",
    r"^Seems dirty\.$": lambda m: f"似乎很脏。",
    r"^Looks fresh\.$": lambda m: f"看起来很新鲜。",
    r"^Sounds fresh\.$": lambda m: f"听起来很新鲜。",
    r"^Feels fresh\.$": lambda m: f"感觉很新鲜。",
    r"^Tastes fresh\.$": lambda m: f"尝起来很新鲜。",
    r"^Smells fresh\.$": lambda m: f"闻起来很新鲜。",
    r"^Seems fresh\.$": lambda m: f"似乎很新鲜。",
    r"^Looks stale\.$": lambda m: f"看起来不新鲜。",
    r"^Sounds stale\.$": lambda m: f"听起来不新鲜。",
    r"^Feels stale\.$": lambda m: f"感觉不新鲜。",
    r"^Tastes stale\.$": lambda m: f"尝起来不新鲜。",
    r"^Smells stale\.$": lambda m: f"闻起来不新鲜。",
    r"^Seems stale\.$": lambda m: f"似乎不新鲜。",
    r"^Looks sweet\.$": lambda m: f"看起来很甜。",
    r"^Sounds sweet\.$": lambda m: f"听起来很甜。",
    r"^Feels sweet\.$": lambda m: f"感觉很甜。",
    r"^Tastes sweet\.$": lambda m: f"尝起来很甜。",
    r"^Smells sweet\.$": lambda m: f"闻起来很甜。",
    r"^Seems sweet\.$": lambda m: f"似乎很甜。",
    r"^Looks sour\.$": lambda m: f"看起来很酸。",
    r"^Sounds sour\.$": lambda m: f"听起来很酸。",
    r"^Feels sour\.$": lambda m: f"感觉很酸。",
    r"^Tastes sour\.$": lambda m: f"尝起来很酸。",
    r"^Smells sour\.$": lambda m: f"闻起来很酸。",
    r"^Seems sour\.$": lambda m: f"似乎很酸。",
    r"^Looks bitter\.$": lambda m: f"看起来很苦。",
    r"^Sounds bitter\.$": lambda m: f"听起来很苦。",
    r"^Feels bitter\.$": lambda m: f"感觉很苦。",
    r"^Tastes bitter\.$": lambda m: f"尝起来很苦。",
    r"^Smells bitter\.$": lambda m: f"闻起来很苦。",
    r"^Seems bitter\.$": lambda m: f"似乎很苦。",
    r"^Looks spicy\.$": lambda m: f"看起来很辣。",
    r"^Sounds spicy\.$": lambda m: f"听起来很辣。",
    r"^Feels spicy\.$": lambda m: f"感觉很辣。",
    r"^Tastes spicy\.$": lambda m: f"尝起来很辣。",
    r"^Smells spicy\.$": lambda m: f"闻起来很辣。",
    r"^Seems spicy\.$": lambda m: f"似乎很辣。",
    r"^Looks hot\.$": lambda m: f"看起来很热。",
    r"^Sounds hot\.$": lambda m: f"听起来很热。",
    r"^Feels hot\.$": lambda m: f"感觉很热。",
    r"^Tastes hot\.$": lambda m: f"尝起来很热。",
    r"^Smells hot\.$": lambda m: f"闻起来很热。",
    r"^Seems hot\.$": lambda m: f"似乎很热。",
    r"^Looks cold\.$": lambda m: f"看起来很冷。",
    r"^Sounds cold\.$": lambda m: f"听起来很冷。",
    r"^Feels cold\.$": lambda m: f"感觉很冷。",
    r"^Tastes cold\.$": lambda m: f"尝起来很冷。",
    r"^Smells cold\.$": lambda m: f"闻起来很冷。",
    r"^Seems cold\.$": lambda m: f"似乎很冷。",
    r"^Looks warm\.$": lambda m: f"看起来很暖和。",
    r"^Sounds warm\.$": lambda m: f"听起来很暖和。",
    r"^Feels warm\.$": lambda m: f"感觉很暖和。",
    r"^Tastes warm\.$": lambda m: f"尝起来很暖和。",
    r"^Smells warm\.$": lambda m: f"闻起来很暖和。",
    r"^Seems warm\.$": lambda m: f"似乎很暖和。",
    r"^Looks cool\.$": lambda m: f"看起来很凉爽。",
    r"^Sounds cool\.$": lambda m: f"听起来很凉爽。",
    r"^Feels cool\.$": lambda m: f"感觉很凉爽。",
    r"^Tastes cool\.$": lambda m: f"尝起来很凉爽。",
    r"^Smells cool\.$": lambda m: f"闻起来很凉爽。",
    r"^Seems cool\.$": lambda m: f"似乎很凉爽。",
    r"^Looks dry\.$": lambda m: f"看起来很干。",
    r"^Sounds dry\.$": lambda m: f"听起来很干。",
    r"^Feels dry\.$": lambda m: f"感觉很干。",
    r"^Tastes dry\.$": lambda m: f"尝起来很干。",
    r"^Smells dry\.$": lambda m: f"闻起来很干。",
    r"^Seems dry\.$": lambda m: f"似乎很干。",
    r"^Looks wet\.$": lambda m: f "看起来很湿。",
    r"^Sounds wet\.$": lambda m: f"听起来很湿。",
    r"^Feels wet\.$": lambda m: f"感觉很湿。",
    r"^Tastes wet\.$": lambda m: f"尝起来很湿。",
    r"^Smells wet\.$": lambda m: f"闻起来很湿。",
    r"^Seems wet\.$": lambda m: f"似乎很湿。",
}

# 常见词汇的中文翻译词典
word_translations = {
    # 学习用品
    "ruler": "尺子", "pencil": "铅笔", "eraser": "橡皮", "crayon": "蜡笔",
    "bag": "书包", "pen": "钢笔", "book": "书", "pencil box": "铅笔盒",
    "schoolbag": "书包", "maths book": "数学书", "English book": "英语书",
    "Chinese book": "语文书", "storybook": "故事书", "notebook": "笔记本",
    "dictionary": "词典", "comic book": "漫画书", "word book": "单词书",
    "postcard": "明信片",
    
    # 颜色
    "red": "红色", "green": "绿色", "yellow": "黄色", "blue": "蓝色",
    "black": "黑色", "brown": "棕色", "white": "白色", "orange": "橙色",
    "pink": "粉色", "purple": "紫色", "grey": "灰色", "gray": "灰色",
    
    # 身体部位
    "face": "脸", "ear": "耳朵", "eye": "眼睛", "nose": "鼻子",
    "mouth": "嘴", "arm": "胳膊", "hand": "手", "head": "头",
    "body": "身体", "leg": "腿", "foot": "脚", "feet": "脚",
    "hair": "头发", "finger": "手指", "toe": "脚趾", "knee": "膝盖",
    "shoulder": "肩膀", "stomach": "胃", "back": "背", "neck": "脖子",
    
    # 动物
    "duck": "鸭子", "pig": "猪", "cat": "猫", "bear": "熊",
    "dog": "狗", "elephant": "大象", "monkey": "猴子", "bird": "鸟",
    "tiger": "老虎", "panda": "熊猫", "zoo": "动物园", "giraffe": "长颈鹿",
    "lion": "狮子", "fox": "狐狸", "wolf": "狼", "rabbit": "兔子",
    "horse": "马", "cow": "牛", "sheep": "绵羊", "hen": "母鸡",
    "chicken": "鸡", "goat": "山羊", "deer": "鹿", "snake": "蛇",
    "mouse": "老鼠", "mice": "老鼠", "rat": "老鼠", "squirrel": "松鼠",
    "kangaroo": "袋鼠", "koala": "考拉", "beaver": "海狸", "otter": "水獭",
    "seal": "海豹", "whale": "鲸鱼", "dolphin": "海豚", "shark": "鲨鱼",
    "fish": "鱼", "goldfish": "金鱼", "turtle": "乌龟", "frog": "青蛙",
    "crocodile": "鳄鱼", "dinosaur": "恐龙", "ant": "蚂蚁", "bee": "蜜蜂",
    "butterfly": "蝴蝶", "dragonfly": "蜻蜓", "mosquito": "蚊子", "fly": "苍蝇",
    "spider": "蜘蛛", "snail": "蜗牛", "worm": "虫子", "caterpillar": "毛毛虫",
    "puppy": "小狗", "kitten": "小猫", "cub": "幼兽", "calf": "小牛",
    "lamb": "小羊", "foal": "小马驹", "piglet": "小猪", "chick": "小鸡",
    
    # 食物
    "bread": "面包", "juice": "果汁", "egg": "蛋", "milk": "牛奶",
    "water": "水", "cake": "蛋糕", "fish": "鱼", "rice": "米饭",
    "beef": "牛肉", "chicken": "鸡肉", "noodles": "面条", "soup": "汤",
    "vegetable": "蔬菜", "pear": "梨", "apple": "苹果", "banana": "香蕉",
    "watermelon": "西瓜", "strawberry": "草莓", "grape": "葡萄",
    "orange": "橙子", "peach": "桃子", "mango": "芒果", "cherry": "樱桃",
    "lemon": "柠檬", "coconut": "椰子", "ham": "火腿", "sandwich": "三明治",
    "hot dog": "热狗", "hamburger": "汉堡包", "pizza": "比萨饼",
    "salad": "沙拉", "cheese": "奶酪", "butter": "黄油", "jam": "果酱",
    "honey": "