// 完整的人教版PEP小学英语单词数据补充部分
// 这部分包含五年级下册、六年级上下册的完整数据

const additionalData = {
  // 五年级下册完整数据
  grade5b: {
    units: [
      {
        unit: 1,
        title: "Unit 1 My day",
        words: [
          {en: "eat breakfast", phonetic: "/iːt ˈbrekfəst/", cn: "吃早饭", example: "I eat breakfast at 7."},
          {en: "have...class", phonetic: "/hæv klɑːs/", cn: "上......课", example: "I have English class."},
          {en: "play sports", phonetic: "/pleɪ ˈspɔːrts/", cn: "做体育运动", example: "I play sports."},
          {en: "exercise", phonetic: "/ˈeksərsaɪz/", cn: "活动；运动", example: "I exercise every day."},
          {en: "do morning exercises", phonetic: "/duː ˈmɔːrnɪŋ ˈeksərsaɪzɪz/", cn: "做早操", example: "Do morning exercises."},
          {en: "eat dinner", phonetic: "/iːt ˈdɪnər/", cn: "吃晚饭", example: "I eat dinner at 6."},
          {en: "clean my room", phonetic: "/kliːn maɪ ruːm/", cn: "打扫房间", example: "I clean my room."},
          {en: "go for a walk", phonetic: "/ɡəʊ fɔːr ə wɔːk/", cn: "散步", example: "Go for a walk."},
          {en: "go shopping", phonetic: "/ɡəʊ ˈʃɒpɪŋ/", cn: "购物", example: "I go shopping."},
          {en: "take", phonetic: "/teɪk/", cn: "学习；上(课)", example: "Take a dancing class."},
          {en: "dancing", phonetic: "/ˈdɑːnsɪŋ/", cn: "跳舞", example: "I like dancing."},
          {en: "when", phonetic: "/wen/", cn: "什么时候", example: "When do you...?"},
          {en: "after", phonetic: "/ˈɑːftər/", cn: "在(时间)后", example: "After school."},
          {en: "start", phonetic: "/stɑːrt/", cn: "开始", example: "School starts."},
          {en: "usually", phonetic: "/ˈjuːʒuəli/", cn: "通常地", example: "I usually..."},
          {en: "Spain", phonetic: "/speɪn/", cn: "西班牙", example: "I'm from Spain."},
          {en: "late", phonetic: "/leɪt/", cn: "晚；迟", example: "Don't be late."},
          {en: "a.m.", phonetic: "/ˌeɪ ˈem/", cn: "午前", example: "At 7 a.m."},
          {en: "p.m.", phonetic: "/ˌpiː ˈem/", cn: "午后", example: "At 3 p.m."},
          {en: "why", phonetic: "/waɪ/", cn: "为什么", example: "Why do you...?"},
          {en: "shop", phonetic: "/ʃɒp/", cn: "去买东西", example: "I go shopping."},
          {en: "work", phonetic: "/wɜːrk/", cn: "工作", example: "I work at night."},
          {en: "last", phonetic: "/lɑːst/", cn: "上一个的", example: "Last weekend."},
          {en: "sound", phonetic: "/saʊnd/", cn: "听起来", example: "That sounds good."},
          {en: "also", phonetic: "/ˈɔːlsəʊ/", cn: "还；也", example: "I also..."},
          {en: "busy", phonetic: "/ˈbɪzi/", cn: "忙的", example: "I'm busy."},
          {en: "need", phonetic: "/niːd/", cn: "需要", example: "I need..."}
        ]
      },
      {
        unit: 2,
        title: "Unit 2 My favourite season",
        words: [
          {en: "spring", phonetic: "/sprɪŋ/", cn: "春天", example: "I like spring."},
          {en: "summer", phonetic: "/ˈsʌmər/", cn: "夏天", example: "I like summer."},
          {en: "autumn", phonetic: "/ˈɔːtəm/", cn: "秋天", example: "I like autumn."},
          {en: "fall", phonetic: "/fɔːl/", cn: "秋天", example: "I like fall."},
          {en: "winter", phonetic: "/ˈwɪntər/", cn: "冬天", example: "I like winter."},
          {en: "season", phonetic: "/ˈsiːzn/", cn: "季节", example: "My favourite season."},
          {en: "picnic", phonetic: "/ˈpɪknɪk/", cn: "野餐", example: "Go on a picnic."},
          {en: "go on a picnic", phonetic: "/ɡəʊ ɒn ə ˈpɪknɪk/", cn: "去野餐", example: "We go on a picnic."},
          {en: "pick", phonetic: "/pɪk/", cn: "摘", example: "Pick apples."},
          {en: "pick apples", phonetic: "/pɪk ˈæplz/", cn: "摘苹果", example: "We pick apples."},
          {en: "snowman", phonetic: "/ˈsnəʊmæn/", cn: "雪人", example: "Make a snowman."},
          {en: "make a snowman", phonetic: "/meɪk ə ˈsnəʊmæn/", cn: "堆雪人", example: "Let's make a snowman."},
          {en: "go swimming", phonetic: "/ɡəʊ ˈswɪmɪŋ/", cn: "去游泳", example: "I go swimming."},
          {en: "which", phonetic: "/wɪtʃ/", cn: "哪一个", example: "Which season?"},
          {en: "best", phonetic: "/best/", cn: "最", example: "I like spring best."},
          {en: "snow", phonetic: "/snəʊ/", cn: "雪", example: "I like snow."},
          {en: "good job", phonetic: "/ɡʊd dʒɒb/", cn: "做得好", example: "Good job!"},
          {en: "because", phonetic: "/bɪˈkɒz/", cn: "因为", example: "Because I like..."},
          {en: "vacation", phonetic: "/veɪˈkeɪʃn/", cn: "假期", example: "Summer vacation."},
          {en: "all", phonetic: "/ɔːl/", cn: "全；完全", example: "All year."},
          {en: "pink", phonetic: "/pɪŋk/", cn: "粉色", example: "I like pink."},
          {en: "lovely", phonetic: "/ˈlʌvli/", cn: "可爱的", example: "Lovely flowers."},
          {en: "leaf", phonetic: "/liːf/", cn: "叶子", example: "Fall leaves."},
          {en: "leaves", phonetic: "/liːvz/", cn: "叶子(复数)", example: "The leaves fall."},
          {en: "paint", phonetic: "/peɪnt/", cn: "用颜料绘画", example: "Paint a picture."}
        ]
      },
      {
        unit: 3,
        title: "Unit 3 My school calendar",
        words: [
          {en: "January", phonetic: "/ˈdʒænjuəri/", cn: "一月", example: "In January."},
          {en: "February", phonetic: "/ˈfebruəri/", cn: "二月", example: "In February."},
          {en: "March", phonetic: "/mɑːtʃ/", cn: "三月", example: "In March."},
          {en: "April", phonetic: "/ˈeɪprəl/", cn: "四月", example: "In April."},
          {en: "May", phonetic: "/meɪ/", cn: "五月", example: "In May."},
          {en: "June", phonetic: "/dʒuːn/", cn: "六月", example: "In June."},
          {en: "July", phonetic: "/dʒuˈlaɪ/", cn: "七月", example: "In July."},
          {en: "August", phonetic: "/ˈɔːɡəst/", cn: "八月", example: "In August."},
          {en: "September", phonetic: "/sepˈtembər/", cn: "九月", example: "In September."},
          {en: "October", phonetic: "/ɒkˈtəʊbər/", cn: "十月", example: "In October."},
          {en: "November", phonetic: "/nəʊˈvembər/", cn: "十一月", example: "In November."},
          {en: "December", phonetic: "/dɪˈsembər/", cn: "十二月", example: "In December."},
          {en: "few", phonetic: "/fjuː/", cn: "不多", example: "A few."},
          {en: "a few", phonetic: "/ə fjuː/", cn: "一些", example: "A few days."},
          {en: "thing", phonetic: "/θɪŋ/", cn: "事情", example: "Fun things."},
          {en: "meet", phonetic: "/miːt/", cn: "集会", example: "Sports meet."},
          {en: "sports meet", phonetic: "/spɔːrts miːt/", cn: "运动会", example: "The sports meet."},
          {en: "Easter", phonetic: "/ˈiːstər/", cn: "复活节", example: "At Easter."},
          {en: "trip", phonetic: "/trɪp/", cn: "旅行", example: "School trip."},
          {en: "year", phonetic: "/jɪər/", cn: "年", example: "This year."},
          {en: "plant", phonetic: "/plɑːnt/", cn: "种植", example: "Plant trees."},
          {en: "contest", phonetic: "/ˈkɒntest/", cn: "比赛", example: "Singing contest."},
          {en: "the Great Wall", phonetic: "/ðə ɡreɪt wɔːl/", cn: "长城", example: "Go to the Great Wall."},
          {en: "national", phonetic: "/ˈnæʃnəl/", cn: "国家的", example: "National Day."},
          {en: "American", phonetic: "/əˈmerɪkən/", cn: "美国的", example: "American Thanksgiving."},
          {en: "Thanksgiving", phonetic: "/ˌθæŋksˈɡɪvɪŋ/", cn: "感恩节", example: "Thanksgiving Day."},
          {en: "Christmas", phonetic: "/ˈkrɪsməs/", cn: "圣诞节", example: "At Christmas."},
          {en: "holiday", phonetic: "/ˈhɒlədeɪ/", cn: "假日", example: "Winter holiday."},
          {en: "game", phonetic: "/ɡeɪm/", cn: "游戏", example: "Play games."},
          {en: "roll", phonetic: "/rəʊl/", cn: "滚动", example: "Roll the eggs."},
          {en: "look for", phonetic: "/lʊk fɔːr/", cn: "寻找", example: "Look for eggs."},
          {en: "chocolate", phonetic: "/ˈtʃɒklət/", cn: "巧克力", example: "I like chocolate."},
          {en: "bunny", phonetic: "/ˈbʌni/", cn: "兔子", example: "Easter bunny."},
          {en: "RSVP", phonetic: "/ˌɑːr es viː ˈpiː/", cn: "请赐复", example: "Please RSVP."},
          {en: "by", phonetic: "/baɪ/", cn: "在......之前", example: "By March 23rd."}
        ]
      },
      {
        unit: 4,
        title: "Unit 4 When is Easter",
        words: [
          {en: "first", phonetic: "/fɜːrst/", cn: "第一(的)", example: "The first day."},
          {en: "second", phonetic: "/ˈsekənd/", cn: "第二(的)", example: "The second day."},
          {en: "third", phonetic: "/θɜːrd/", cn: "第三(的)", example: "The third day."},
          {en: "fourth", phonetic: "/fɔːrθ/", cn: "第四(的)", example: "The fourth day."},
          {en: "fifth", phonetic: "/fɪfθ/", cn: "第五(的)", example: "The fifth day."},
          {en: "twelfth", phonetic: "/twelfθ/", cn: "第十二(的)", example: "The twelfth day."},
          {en: "twentieth", phonetic: "/ˈtwentiəθ/", cn: "第二十(的)", example: "The twentieth day."},
          {en: "twenty-first", phonetic: "/ˌtwenti ˈfɜːrst/", cn: "第二十一(的)", example: "The twenty-first day."},
          {en: "twenty-third", phonetic: "/ˌtwenti θɜːrd/", cn: "第二十三(的)", example: "The twenty-third day."},
          {en: "thirtieth", phonetic: "/ˈθɜːrtiəθ/", cn: "第三十(的)", example: "The thirtieth day."},
          {en: "special", phonetic: "/ˈspeʃl/", cn: "特殊的", example: "A special day."},
          {en: "fool", phonetic: "/fuːl/", cn: "蠢人", example: "April Fool's Day."},
          {en: "kitten", phonetic: "/ˈkɪtn/", cn: "小猫", example: "A cute kitten."},
          {en: "diary", phonetic: "/ˈdaɪəri/", cn: "日记", example: "Write a diary."},
          {en: "still", phonetic: "/stɪl/", cn: "仍然", example: "Still young."},
          {en: "noise", phonetic: "/nɔɪz/", cn: "声音", example: "Make noises."},
          {en: "fur", phonetic: "/fɜːr/", cn: "皮毛", example: "White fur."},
          {en: "open", phonetic: "/ˈəʊpən/", cn: "开着的", example: "Open eyes."},
          {en: "walk", phonetic: "/wɔːk/", cn: "行走", example: "Walk around."}
        ]
      },
      {
        unit: 5,
        title: "Unit 5 Whose dog is it",
        words: [
          {en: "mine", phonetic: "/maɪn/", cn: "我的", example: "It's mine."},
          {en: "yours", phonetic: "/jɔːrz/", cn: "你的", example: "It's yours."},
          {en: "his", phonetic: "/hɪz/", cn: "他的", example: "It's his."},
          {en: "hers", phonetic: "/hɜːrz/", cn: "她的", example: "It's hers."},
          {en: "theirs", phonetic: "/ðeərz/", cn: "他们的", example: "It's theirs."},
          {en: "ours", phonetic: "/ˈaʊərz/", cn: "我们的", example: "It's ours."},
          {en: "climbing", phonetic: "/ˈklaɪmɪŋ/", cn: "攀登", example: "Is climbing."},
          {en: "eating", phonetic: "/ˈiːtɪŋ/", cn: "吃", example: "Is eating."},
          {en: "playing", phonetic: "/ˈpleɪɪŋ/", cn: "玩耍", example: "Is playing."},
          {en: "jumping", phonetic: "/ˈdʒʌmpɪŋ/", cn: "跳", example: "Is jumping."},
          {en: "drinking", phonetic: "/ˈdrɪŋkɪŋ/", cn: "喝", example: "Is drinking."},
          {en: "sleeping", phonetic: "/ˈsliːpɪŋ/", cn: "睡觉", example: "Is sleeping."},
          {en: "each", phonetic: "/iːtʃ/", cn: "每个", example: "Each other."},
          {en: "other", phonetic: "/ˈʌðər/", cn: "其他", example: "Each other."},
          {en: "each other", phonetic: "/iːtʃ ˈʌðər/", cn: "相互", example: "Play with each other."},
          {en: "excited", phonetic: "/ɪkˈsaɪtɪd/", cn: "兴奋的", example: "I'm excited."},
          {en: "like", phonetic: "/laɪk/", cn: "像......那样", example: "Like flying."}
        ]
      },
      {
        unit: 6,
        title: "Unit 6 Work quietly",
        words: [
          {en: "doing morning exercises", phonetic: "/ˈduːɪŋ ˈmɔːrnɪŋ ˈeksərsaɪzɪz/", cn: "做早操", example: "Are doing morning exercises."},
          {en: "having...class", phonetic: "/ˈhævɪŋ klɑːs/", cn: "上......课", example: "Are having English class."},
          {en: "eating lunch", phonetic: "/ˈiːtɪŋ lʌntʃ/", cn: "吃午饭", example: "Are eating lunch."},
          {en: "reading a book", phonetic: "/ˈriːdɪŋ ə bʊk/", cn: "看书", example: "Is reading a book."},
          {en: "listening to music", phonetic: "/ˈlɪsənɪŋ tuː ˈmjuːzɪk/", cn: "听音乐", example: "Is listening to music."},
          {en: "keep", phonetic: "/kiːp/", cn: "保持", example: "Keep to the right."},
          {en: "keep to the right", phonetic: "/kiːp tuː ðə raɪt/", cn: "靠右", example: "Keep to the right."},
          {en: "keep your desk clean", phonetic: "/kiːp jɔːr desk kliːn/", cn: "保持桌面整洁", example: "Keep your desk clean."},
          {en: "talk quietly", phonetic: "/tɔːk ˈkwaɪətli/", cn: "小声讲话", example: "Talk quietly."},
          {en: "turn", phonetic: "/tɜːrn/", cn: "顺序", example: "Take turns."},
          {en: "take turns", phonetic: "/teɪk tɜːrnz/", cn: "按顺序来", example: "Take turns."},
          {en: "bamboo", phonetic: "/ˌbæmˈbuː/", cn: "竹子", example: "Bamboo shoots."},
          {en: "its", phonetic: "/ɪts/", cn: "它的", example: "Its eyes."},
          {en: "show", phonetic: "/ʃəʊ/", cn: "给人看", example: "Show me."},
          {en: "anything", phonetic: "/ˈeniθɪŋ/", cn: "任何事", example: "Do anything."},
          {en: "else", phonetic: "/els/", cn: "另外", example: "What else?"},
          {en: "exhibition", phonetic: "/ˌeksɪˈbɪʃn/", cn: "展览", example: "Art exhibition."},
          {en: "say", phonetic: "/seɪ/", cn: "说", example: "Say something."},
          {en: "have a look", phonetic: "/hæv ə lʊk/", cn: "看一看", example: "Have a look."},
          {en: "sushi", phonetic: "/ˈsuːʃi/", cn: "寿司", example: "I like sushi."},
          {en: "teach", phonetic: "/tiːtʃ/", cn: "教", example: "Teach English."},
          {en: "sure", phonetic: "/ʃʊər/", cn: "当然", example: "Sure."},
          {en: "Canadian", phonetic: "/kəˈneɪdiən/", cn: "加拿大的", example: "I'm Canadian."},
          {en: "Spanish", phonetic: "/ˈspænɪʃ/", cn: "西班牙的", example: "I'm Spanish."},
          {en: "American", phonetic: "/əˈmerɪkən/", cn: "美国的", example: "I'm American."}
        ]
      }
    ]
  },
  // 六年级上册完整数据
  grade6: {
    units: [
      {
        unit: 1,
        title: "Unit 1 How can I get there",
        words: [
          {en: "science", phonetic: "/ˈsaɪəns/", cn: "科学", example: "I like science."},
          {en: "museum", phonetic: "/mjuˈziːəm/", cn: "博物馆", example: "Go to the museum."},
          {en: "post office", phonetic: "/pəʊst ˈɒfɪs/", cn: "邮局", example: "At the post office."},
          {en: "bookstore", phonetic: "/ˈbʊkstɔːr/", cn: "书店", example: "In the bookstore."},
          {en: "cinema", phonetic: "/ˈsɪnəmə/", cn: "电影院", example: "At the cinema."},
          {en: "hospital", phonetic: "/ˈhɒspɪtl/", cn: "医院", example: "Go to the hospital."},
          {en: "crossing", phonetic: "/ˈkrɒsɪŋ/", cn: "十字路口", example: "At the crossing."},
          {en: "turn", phonetic: "/tɜːrn/", cn: "转弯", example: "Turn left."},
          {en: "left", phonetic: "/left/", cn: "左", example: "Turn left."},
          {en: "straight", phonetic: "/streɪt/", cn: "笔直地", example: "Go straight."},
          {en: "right", phonetic: "/raɪt/", cn: "右", example: "Turn right."},
          {en: "ask", phonetic: "/ɑːsk/", cn: "问", example: "Ask the way."},
          {en: "sir", phonetic: "/sɜːr/", cn: "先生", example: "Excuse me, sir."},
          {en: "interesting", phonetic: "/ˈɪntrəstɪŋ/", cn: "有趣的", example: "It's interesting."},
          {en: "Italian", phonetic: "/ɪˈtæliən/", cn: "意大利的", example: "Italian food."},
          {en: "restaurant", phonetic: "/ˈrestrɒnt/", cn: "餐馆", example: "At the restaurant."},
          {en: "pizza", phonetic: "/ˈpiːtsə/", cn: "比萨饼", example: "I like pizza."},
          {en: "street", phonetic: "/striːt/", cn: "大街", example: "On the street."},
          {en: "get", phonetic: "/ɡet/", cn: "到达", example: "Get there."},
          {en: "GPS", phonetic: "/ˌdʒiː piː ˈes/", cn: "导航", example: "Use GPS."},
          {en: "gave", phonetic: "/ɡeɪv/", cn: "提供(give的过去式)", example: "He gave me..."},
          {en: "feature", phonetic: "/ˈfiːtʃər/", cn: "特点", example: "A new feature."},
          {en: "follow", phonetic: "/ˈfɒləʊ/", cn: "跟着", example: "Follow me."},
          {en: "far", phonetic: "/fɑːr/", cn: "较远的", example: "It's far."},
          {en: "tell", phonetic: "/tel/", cn: "告诉", example: "Tell me."}
        ]
      },
      {
        unit: 2,
        title: "Unit 2 Ways to go to school",
        words: [
          {en: "on foot", phonetic: "/ɒn fʊt/", cn: "步行", example: "I go on foot."},
          {en: "by", phonetic: "/baɪ/", cn: "乘", example: "By bus."},
          {en: "bus", phonetic: "/bʌs/", cn: "公共汽车", example: "By bus."},
          {en: "plane", phonetic: "/pleɪn/", cn: "飞机", example: "By plane."},
          {en: "taxi", phonetic: "/ˈtæksi/", cn: "出租汽车", example: "By taxi."},
          {en: "ship", phonetic: "/ʃɪp/", cn: "船", example: "By ship."},
          {en: "subway", phonetic: "/ˈsʌbweɪ/", cn: "地铁", example: "By subway."},
          {en: "train", phonetic: "/treɪn/", cn: "火车", example: "By train."},
          {en: "slow", phonetic: "/sləʊ/", cn: "慢的", example: "Slow down."},
          {en: "down", phonetic: "/daʊn/", cn: "减少；降低", example: "Slow down."},
          {en: "slow down", phonetic: "/sləʊ daʊn/", cn: "慢下来", example: "Slow down."},
          {en: "stop", phonetic: "/stɒp/", cn: "停下", example: "Stop."},
          {en: "wait", phonetic: "/weɪt/", cn: "等待", example: "Wait."},
          {en: "Mrs", phonetic: "/ˈmɪsɪz/", cn: "夫人", example: "Mrs Smith."},
          {en: "early", phonetic: "/ˈɜːrli/", cn: "早到的", example: "Be early."},
          {en: "helmet", phonetic: "/ˈhelmɪt/", cn: "头盔", example: "Wear a helmet."},
          {en: "must", phonetic: "/mʌst/", cn: "必须", example: "You must..."},
          {en: "wear", phonetic: "/weər/", cn: "戴", example: "Wear a helmet."},
          {en: "attention", phonetic: "/əˈtenʃn/", cn: "注意", example: "Pay attention."},
          {en: "pay attention to", phonetic: "/peɪ əˈtenʃn tuː/", cn: "注意", example: "Pay attention to..."},
          {en: "traffic", phonetic: "/ˈtræfɪk/", cn: "交通", example: "Traffic lights."},
          {en: "traffic lights", phonetic: "/ˈtræfɪk laɪts/", cn: "交通信号灯", example: "Look at traffic lights."},
          {en: "Munich", phonetic: "/ˈmjuːnɪk/", cn: "慕尼黑", example: "In Munich."},
          {en: "Germany", phonetic: "/ˈdʒɜːrməni/", cn: "德国", example: "In Germany."},
          {en: "Alaska", phonetic: "/əˈlæskə/", cn: "阿拉斯加州", example: "In Alaska."},
          {en: "sled", phonetic: "/sled/", cn: "雪橇", example: "By sled."},
          {en: "fast", phonetic: "/fɑːst/", cn: "快的", example: "Fast and fun."},
          {en: "ferry", phonetic: "/ˈferi/", cn: "轮渡", example: "By ferry."},
          {en: "Papa Westray", phonetic: "/ˈpɑːpə ˈwestreɪ/", cn: "帕帕韦斯特雷岛", example: "Papa Westray."},
          {en: "Scotland", phonetic: "/ˈskɒtlənd/", cn: "苏格兰", example: "In Scotland."}
        ]
      },
      {
        unit: 3,
        title: "Unit 3 My weekend plan",
        words: [
          {en: "visit", phonetic: "/ˈvɪzɪt/", cn: "拜访", example: "Visit my grandparents."},
          {en: "film", phonetic: "/fɪlm/", cn: "电影", example: "See a film."},
          {en: "see a film", phonetic: "/siː ə fɪlm/", cn: "看电影", example: "I'm going to see a film."},
          {en: "trip", phonetic: "/trɪp/", cn: "旅行", example: "Take a trip."},
          {en: "take a trip", phonetic: "/teɪk ə trɪp/", cn: "去旅行", example: "I'm going to take a trip."},
          {en: "supermarket", phonetic: "/ˈsuːpəmɑːrkɪt/", cn: "超市", example: "Go to the supermarket."},
          {en: "evening", phonetic: "/ˈiːvnɪŋ/", cn: "晚上", example: "This evening."},
          {en: "tonight", phonetic: "/təˈnaɪt/", cn: "在今晚", example: "Tonight."},
          {en: "tomorrow", phonetic: "/təˈmɒrəʊ/", cn: "明天", example: "Tomorrow."},
          {en: "next week", phonetic: "/nekst wiːk/", cn: "下周", example: "Next week."},
          {en: "dictionary", phonetic: "/ˈdɪkʃəneri/", cn: "词典", example: "A dictionary."},
          {en: "comic", phonetic: "/ˈkɒmɪk/", cn: "滑稽的", example: "Comic book."},
          {en: "comic book", phonetic: "/ˈkɒmɪk bʊk/", cn: "连环画册", example: "Buy a comic book."},
          {en: "word book", phonetic: "/wɜːrd bʊk/", cn: "单词书", example: "Buy a word book."},
          {en: "postcard", phonetic: "/ˈpəʊstkɑːrd/", cn: "明信片", example: "Buy a postcard."},
          {en: "lesson", phonetic: "/ˈlesn/", cn: "课", example: "Take a lesson."},
          {en: "space", phonetic: "/speɪs/", cn: "太空", example: "Space travel."},
          {en: "travel", phonetic: "/ˈtrævl/", cn: "旅行", example: "Space travel."},
          {en: "half price", phonetic: "/hɑːf praɪs/", cn: "半价", example: "Half price."},
          {en: "moon", phonetic: "/muːn/", cn: "月亮", example: "Go to the moon."},
          {en: "get together", phonetic: "/ɡet təˈɡeðər/", cn: "聚会", example: "Get together."},
          {en: "poem", phonetic: "/ˈpəʊɪm/", cn: "诗", example: "Read a poem."},
          {en: "mooncake", phonetic: "/ˈmuːnkeɪk/", cn: "月饼", example: "Eat mooncakes."}
        ]
      },
      {
        unit: 4,
        title: "Unit 4 I have a pen pal",
        words: [
          {en: "studies", phonetic: "/ˈstʌdiz/", cn: "学习", example: "He studies Chinese."},
          {en: "puzzle", phonetic: "/ˈpʌzl/", cn: "谜", example: "Do word puzzles."},
          {en: "hiking", phonetic: "/ˈhaɪkɪŋ/", cn: "远足", example: "Go hiking."},
          {en: "jasmine", phonetic: "/ˈdʒæzmɪn/", cn: "茉莉", example: "Jasmine flower."},
          {en: "idea", phonetic: "/aɪˈdɪə/", cn: "想法", example: "Good idea."},
          {en: "Canberra", phonetic: "/ˈkænbərə/", cn: "堪培拉", example: "In Canberra."},
          {en: "amazing", phonetic: "/əˈmeɪzɪŋ/", cn: "令人惊奇的", example: "That's amazing."},
          {en: "shall", phonetic: "/ʃæl/", cn: "表示征求意见", example: "Shall we...?"},
          {en: "goal", phonetic: "/ɡəʊl/", cn: "射门", example: "Score a goal."},
          {en: "join", phonetic: "/dʒɔɪn/", cn: "加入", example: "Join us."},
          {en: "club", phonetic: "/klʌb/", cn: "俱乐部", example: "Join the club."},
          {en: "share", phonetic: "/ʃeər/", cn: "分享", example: "Share with me."}
        ]
      },
      {
        unit: 5,
        title: "Unit 5 What does he do",
        words: [
          {en: "factory worker", phonetic: "/ˈfæktri ˈwɜːrkər/", cn: "工厂工人", example: "He's a factory worker."},
          {en: "postman", phonetic: "/ˈpəʊstmən/", cn: "邮递员", example: "He's a postman."},
          {en: "businessman", phonetic: "/ˈbɪznəsmæn/", cn: "商人", example: "He's a businessman."},
          {en: "police officer", phonetic: "/pəˈliːs ˈɒfɪsər/", cn: "警察", example: "He's a police officer."},
          {en: "fisherman", phonetic: "/ˈfɪʃərmən/", cn: "渔民", example: "He's a fisherman."},
          {en: "scientist", phonetic: "/ˈsaɪəntɪst/", cn: "科学家", example: "He's a scientist."},
          {en: "pilot", phonetic: "/ˈpaɪlət/", cn: "飞行员", example: "He's a pilot."},
          {en: "coach", phonetic: "/kəʊtʃ/", cn: "教练", example: "He's a coach."},
          {en: "country", phonetic: "/ˈkʌntri/", cn: "国家", example: "In this country."},
          {en: "head teacher", phonetic: "/hed ˈtiːtʃər/", cn: "校长", example: "She's a head teacher."},
          {en: "sea", phonetic: "/siː/", cn: "大海", example: "By the sea."},
          {en: "stay", phonetic: "/steɪ/", cn: "保持", example: "Stay healthy."},
          {en: "university", phonetic: "/ˌjuːnɪˈvɜːrsəti/", cn: "大学", example: "At a university."},
          {en: "gym", phonetic: "/dʒɪm/", cn: "体育馆", example: "In a gym."},
          {en: "if", phonetic: "/ɪf/", cn: "如果", example: "If you like..."},
          {en: "reporter", phonetic: "/rɪˈpɔːrtər/", cn: "记者", example: "He's a reporter."},
          {en: "use", phonetic: "/juːz/", cn: "使用", example: "Use a computer."},
          {en: "type", phonetic: "/taɪp/", cn: "打字", example: "Type quickly."},
          {en: "quickly", phonetic: "/ˈkwɪkli/", cn: "迅速地", example: "Type quickly."},
          {en: "secretary", phonetic: "/ˈsekrəteri/", cn: "秘书", example: "She's a secretary."}
        ]
      },
      {
        unit: 6,
        title: "Unit 6 How do you feel",
        words: [
          {en: "angry", phonetic: "/ˈæŋɡri/", cn: "生气的", example: "I'm angry."},
          {en: "afraid", phonetic: "/əˈfreɪd/", cn: "害怕", example: "I'm afraid."},
          {en: "sad", phonetic: "/sæd/", cn: "难过的", example: "I'm sad."},
          {en: "worried", phonetic: "/ˈwʌrid/", cn: "担心的", example: "I'm worried."},
          {en: "happy", phonetic: "/ˈhæpi/", cn: "高兴的", example: "I'm happy."},
          {en: "see a doctor", phonetic: "/siː ə ˈdɒktər/", cn: "看病", example: "You should see a doctor."},
          {en: "wear", phonetic: "/weər/", cn: "穿", example: "Wear warm clothes."},
          {en: "more", phonetic: "/mɔːr/", cn: "更多的", example: "Do more exercise."},
          {en: "deep", phonetic: "/diːp/", cn: "深的", example: "Take a deep breath."},
          {en: "breath", phonetic: "/breθ/", cn: "呼吸", example: "Take a breath."},
          {en: "take a deep breath", phonetic: "/teɪk ə diːp breθ/", cn: "深深吸一口气", example: "Take a deep breath."},
          {en: "count", phonetic: "/kaʊnt/", cn: "数数", example: "Count to ten."},
          {en: "count to ten", phonetic: "/kaʊnt tuː ten/", cn: "数到十", example: "Count to ten."}
        ]
      }
    ]
  },
  // 六年级下册完整数据
  grade6b: {
    units: [
      {
        unit: 1,
        title: "Unit 1 How tall are you",
        words: [
          {en: "taller", phonetic: "/ˈtɔːlər/", cn: "更高的", example: "I'm taller."},
          {en: "shorter", phonetic: "/ˈʃɔːrtər/", cn: "更矮的", example: "He's shorter."},
          {en: "stronger", phonetic: "/ˈstrɒŋɡər/", cn: "更强壮的", example: "He's stronger."},
          {en: "older", phonetic: "/ˈəʊldər/", cn: "更年长的", example: "I'm older."},
          {en: "younger", phonetic: "/ˈjʌŋɡər/", cn: "更年轻的", example: "She's younger."},
          {en: "bigger", phonetic: "/ˈbɪɡər/", cn: "更大的", example: "It's bigger."},
          {en: "smaller", phonetic: "/ˈsmɔːlər/", cn: "更小的", example: "It's smaller."},
          {en: "metre", phonetic: "/ˈmiːtər/", cn: "米", example: "I'm 1.6 metres."},
          {en: "than", phonetic: "/ðæn/", cn: "比", example: "Taller than me."},
          {en: "dinosaur", phonetic: "/ˈdaɪnəsɔːr/", cn: "恐龙", example: "A big dinosaur."},
          {en: "hall", phonetic: "/hɔːl/", cn: "大厅", example: "In the hall."},
          {en: "dining hall", phonetic: "/ˈdaɪnɪŋ hɔːl/", cn: "饭厅", example: "In the dining hall."},
          {en: "both", phonetic: "/bəʊθ/", cn: "两个都", example: "We both..."},
          {en: "kilogram", phonetic: "/ˈkɪləɡræm/", cn: "千克", example: "40 kilograms."},
          {en: "countryside", phonetic: "/ˈkʌntrisaɪd/", cn: "乡村", example: "In the countryside."},
          {en: "lower", phonetic: "/ˈləʊər/", cn: "更低的", example: "Lower and lower."},
          {en: "shadow", phonetic: "/ˈʃædəʊ/", cn: "影子", example: "My shadow."},
          {en: "smarter", phonetic: "/ˈsmɑːrtər/", cn: "更聪明的", example: "I'm smarter."},
          {en: "become", phonetic: "/bɪˈkʌm/", cn: "开始变得", example: "Become longer."}
        ]
      },
      {
        unit: 2,
        title: "Unit 2 Last weekend",
        words: [
          {en: "cleaned", phonetic: "/kliːnd/", cn: "打扫", example: "I cleaned my room."},
          {en: "stayed", phonetic: "/steɪd/", cn: "停留", example: "I stayed at home."},
          {en: "washed", phonetic: "/wɒʃt/", cn: "洗", example: "I washed my clothes."},
          {en: "watched", phonetic: "/wɒtʃt/", cn: "看", example: "I watched TV."},
          {en: "had", phonetic: "/hæd/", cn: "有", example: "I had a cold."},
          {en: "had a cold", phonetic: "/hæd ə kəʊld/", cn: "感冒", example: "I had a cold."},
          {en: "slept", phonetic: "/slept/", cn: "睡觉", example: "I slept late."},
          {en: "read", phonetic: "/riːd/", cn: "读", example: "I read a book."},
          {en: "saw", phonetic: "/sɔː/", cn: "看见", example: "I saw a film."},
          {en: "last", phonetic: "/lɑːst/", cn: "最近的", example: "Last weekend."},
          {en: "yesterday", phonetic: "/ˈjestərdeɪ/", cn: "昨天", example: "Yesterday."},
          {en: "before", phonetic: "/bɪˈfɔːr/", cn: "在......之前", example: "The day before yesterday."},
          {en: "drank", phonetic: "/dræŋk/", cn: "喝", example: "I drank tea."},
          {en: "show", phonetic: "/ʃəʊ/", cn: "演出", example: "A fashion show."},
          {en: "magazine", phonetic: "/ˌmæɡəˈziːn/", cn: "杂志", example: "A magazine."},
          {en: "better", phonetic: "/ˈbetər/", cn: "更好的", example: "Feel better."},
          {en: "faster", phonetic: "/ˈfæstər/", cn: "更快的", example: "Run faster."},
          {en: "hotel", phonetic: "/həʊˈtel/", cn: "旅馆", example: "In a hotel."},
          {en: "fixed", phonetic: "/fɪkst/", cn: "修理", example: "I fixed the bike."},
          {en: "broken", phonetic: "/ˈbrəʊkən/", cn: "破损的", example: "A broken bike."},
          {en: "lamp", phonetic: "/læmp/", cn: "台灯", example: "A lamp."},
          {en: "loud", phonetic: "/laʊd/", cn: "大声的", example: "Too loud."},
          {en: "enjoy", phonetic: "/ɪnˈdʒɔɪ/", cn: "享受", example: "Enjoy the moon."},
          {en: "stay", phonetic: "/steɪ/", cn: "暂住", example: "Stay with us."}
        ]
      },
      {
        unit: 3,
        title: "Unit 3 Where did you go",
        words: [
          {en: "went", phonetic: "/went/", cn: "去", example: "I went to..."},
          {en: "camp", phonetic: "/kæmp/", cn: "野营", example: "Go camping."},
          {en: "went camping", phonetic: "/went ˈkæmpɪŋ/", cn: "去野营", example: "I went camping."},
          {en: "fish", phonetic: "/fɪʃ/", cn: "钓鱼", example: "Go fishing."},
          {en: "went fishing", phonetic: "/went ˈfɪʃɪŋ/", cn: "去钓鱼", example: "I went fishing."},
          {en: "rode", phonetic: "/rəʊd/", cn: "骑", example: "I rode a bike."},
          {en: "hurt", phonetic: "/hɜːrt/", cn: "受伤", example: "I hurt my foot."},
          {en: "ate", phonetic: "/et/", cn: "吃", example: "I ate fresh food."},
          {en: "took", phonetic: "/tʊk/", cn: "拍照", example: "I took pictures."},
          {en: "took pictures", phonetic: "/tʊk ˈpɪktʃərz/", cn: "照相", example: "I took pictures."},
          {en: "bought", phonetic: "/bɔːt/", cn: "买", example: "I bought gifts."},
          {en: "gift", phonetic: "/ɡɪft/", cn: "礼物", example: "Buy gifts."},
          {en: "fell", phonetic: "/fel/", cn: "摔倒", example: "I fell off."},
          {en: "off", phonetic: "/ɒf/", cn: "从......落下", example: "Fall off."},
          {en: "fell off", phonetic: "/fel ɒf/", cn: "从......摔下来", example: "I fell off."},
          {en: "Labour Day", phonetic: "/ˈleɪbər deɪ/", cn: "劳动节", example: "On Labour Day."},
          {en: "mule", phonetic: "/mjuːl/", cn: "骡子", example: "Ride a mule."},
          {en: "Turpan", phonetic: "/ˈtʊəpɑːn/", cn: "吐鲁番", example: "In Turpan."},
          {en: "could", phonetic: "/kʊd/", cn: "能", example: "I could..."},
          {en: "till", phonetic: "/tɪl/", cn: "直到", example: "Till next time."}
        ]
      },
      {
        unit: 4,
        title: "Unit 4 Then and now",
        words: [
          {en: "dining hall", phonetic: "/ˈdaɪnɪŋ hɔːl/", cn: "饭厅", example: "In the dining hall."},
          {en: "grass", phonetic: "/ɡrɑːs/", cn: "草坪", example: "On the grass."},
          {en: "gym", phonetic: "/dʒɪm/", cn: "体育馆", example: "In the gym."},
          {en: "ago", phonetic: "/əˈɡəʊ/", cn: "以前", example: "Years ago."},
          {en: "cycling", phonetic: "/ˈsaɪklɪŋ/", cn: "骑自行车运动", example: "Go cycling."},
          {en: "go cycling", phonetic: "/ɡəʊ ˈsaɪklɪŋ/", cn: "去骑自行车", example: "I went cycling."},
          {en: "ice-skate", phonetic: "/ˈaɪs skeɪt/", cn: "滑冰", example: "Go ice-skating."},
          {en: "badminton", phonetic: "/ˈbædmɪntən/", cn: "羽毛球", example: "Play badminton."},
          {en: "star", phonetic: "/stɑːr/", cn: "星", example: "A movie star."},
          {en: "easy", phonetic: "/ˈiːzi/", cn: "容易的", example: "It's easy."},
          {en: "look up", phonetic: "/lʊk ʌp/", cn: "查阅", example: "Look it up."},
          {en: "Internet", phonetic: "/ˈɪntərnet/", cn: "互联网", example: "On the Internet."},
          {en: "different", phonetic: "/ˈdɪfrənt/", cn: "不同的", example: "Very different."},
          {en: "active", phonetic: "/ˈæktɪv/", cn: "积极的", example: "Be active."},
          {en: "race", phonetic: "/reɪs/", cn: "赛跑", example: "A race."},
          {en: "nothing", phonetic: "/ˈnʌθɪŋ/", cn: "没有什么", example: "Nothing."},
          {en: "thought", phonetic: "/θɔːt/", cn: "想", example: "I thought..."},
          {en: "felt", phonetic: "/felt/", cn: "感觉", example: "I felt happy."},
          {en: "cheetah", phonetic: "/ˈtʃiːtə/", cn: "猎豹", example: "A cheetah."},
          {en: "trip", phonetic: "/trɪp/", cn: "绊倒", example: "Trip over."},
          {en: "woke", phonetic: "/wəʊk/", cn: "醒", example: "I woke up."},
          {en: "dream", phonetic: "/driːm/", cn: "梦", example: "A dream."}
        ]
      }
    ]
  }
};

module.exports = additionalData;
